// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	v1 "github.com/kinneko-de/api-contract/golang/kinnekode/restaurant/document/v1"
)

// DocumentService_GeneratePreviewServer is an autogenerated mock type for the DocumentService_GeneratePreviewServer type
type DocumentService_GeneratePreviewServer struct {
	mock.Mock
}

type DocumentService_GeneratePreviewServer_Expecter struct {
	mock *mock.Mock
}

func (_m *DocumentService_GeneratePreviewServer) EXPECT() *DocumentService_GeneratePreviewServer_Expecter {
	return &DocumentService_GeneratePreviewServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *DocumentService_GeneratePreviewServer) Context() context.Context {
	ret := _m.Called()

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// DocumentService_GeneratePreviewServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type DocumentService_GeneratePreviewServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *DocumentService_GeneratePreviewServer_Expecter) Context() *DocumentService_GeneratePreviewServer_Context_Call {
	return &DocumentService_GeneratePreviewServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *DocumentService_GeneratePreviewServer_Context_Call) Run(run func()) *DocumentService_GeneratePreviewServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_Context_Call) Return(_a0 context.Context) *DocumentService_GeneratePreviewServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_Context_Call) RunAndReturn(run func() context.Context) *DocumentService_GeneratePreviewServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *DocumentService_GeneratePreviewServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentService_GeneratePreviewServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type DocumentService_GeneratePreviewServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *DocumentService_GeneratePreviewServer_Expecter) RecvMsg(m interface{}) *DocumentService_GeneratePreviewServer_RecvMsg_Call {
	return &DocumentService_GeneratePreviewServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *DocumentService_GeneratePreviewServer_RecvMsg_Call) Run(run func(m interface{})) *DocumentService_GeneratePreviewServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_RecvMsg_Call) Return(_a0 error) *DocumentService_GeneratePreviewServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *DocumentService_GeneratePreviewServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *DocumentService_GeneratePreviewServer) Send(_a0 *v1.GeneratePreviewResponse) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.GeneratePreviewResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentService_GeneratePreviewServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type DocumentService_GeneratePreviewServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *v1.GeneratePreviewResponse
func (_e *DocumentService_GeneratePreviewServer_Expecter) Send(_a0 interface{}) *DocumentService_GeneratePreviewServer_Send_Call {
	return &DocumentService_GeneratePreviewServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *DocumentService_GeneratePreviewServer_Send_Call) Run(run func(_a0 *v1.GeneratePreviewResponse)) *DocumentService_GeneratePreviewServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.GeneratePreviewResponse))
	})
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_Send_Call) Return(_a0 error) *DocumentService_GeneratePreviewServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_Send_Call) RunAndReturn(run func(*v1.GeneratePreviewResponse) error) *DocumentService_GeneratePreviewServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *DocumentService_GeneratePreviewServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentService_GeneratePreviewServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type DocumentService_GeneratePreviewServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *DocumentService_GeneratePreviewServer_Expecter) SendHeader(_a0 interface{}) *DocumentService_GeneratePreviewServer_SendHeader_Call {
	return &DocumentService_GeneratePreviewServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *DocumentService_GeneratePreviewServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *DocumentService_GeneratePreviewServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SendHeader_Call) Return(_a0 error) *DocumentService_GeneratePreviewServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *DocumentService_GeneratePreviewServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *DocumentService_GeneratePreviewServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentService_GeneratePreviewServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type DocumentService_GeneratePreviewServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *DocumentService_GeneratePreviewServer_Expecter) SendMsg(m interface{}) *DocumentService_GeneratePreviewServer_SendMsg_Call {
	return &DocumentService_GeneratePreviewServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *DocumentService_GeneratePreviewServer_SendMsg_Call) Run(run func(m interface{})) *DocumentService_GeneratePreviewServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SendMsg_Call) Return(_a0 error) *DocumentService_GeneratePreviewServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SendMsg_Call) RunAndReturn(run func(interface{}) error) *DocumentService_GeneratePreviewServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *DocumentService_GeneratePreviewServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DocumentService_GeneratePreviewServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type DocumentService_GeneratePreviewServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *DocumentService_GeneratePreviewServer_Expecter) SetHeader(_a0 interface{}) *DocumentService_GeneratePreviewServer_SetHeader_Call {
	return &DocumentService_GeneratePreviewServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *DocumentService_GeneratePreviewServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *DocumentService_GeneratePreviewServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SetHeader_Call) Return(_a0 error) *DocumentService_GeneratePreviewServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *DocumentService_GeneratePreviewServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *DocumentService_GeneratePreviewServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// DocumentService_GeneratePreviewServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type DocumentService_GeneratePreviewServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *DocumentService_GeneratePreviewServer_Expecter) SetTrailer(_a0 interface{}) *DocumentService_GeneratePreviewServer_SetTrailer_Call {
	return &DocumentService_GeneratePreviewServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *DocumentService_GeneratePreviewServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *DocumentService_GeneratePreviewServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SetTrailer_Call) Return() *DocumentService_GeneratePreviewServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *DocumentService_GeneratePreviewServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *DocumentService_GeneratePreviewServer_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewDocumentService_GeneratePreviewServer creates a new instance of DocumentService_GeneratePreviewServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentService_GeneratePreviewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentService_GeneratePreviewServer {
	mock := &DocumentService_GeneratePreviewServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
